### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Shalfey-334** [hts1238/yandex_project#11]
При нажатии на "выход" закрывает приложение. Вообще было бы неплохо исключить постоянные закрывания приложения, как после регистрации, так и после нажатия на выход. Для закрытия приложения есть кнопка в правом верхнем углу. 
Если нажать "ок" при входе не вводя данные, создаст нового пользователя с пустой строкой вместо имени. Данный пользователь не может писать самому себе. Это надо исправить, он должен иметь те же права, что и остальные пользователи. Еще скорее всего все, кто будут вводить пустые строки вместо имен будут входить под один аккаунт. Вполне вероятно также, что это возникло из-за того, что кто-то завершил регистрацию, не введя данных. Решается простым ограничением минимального количества символов в регистрационных данных. 
Ну и консоль на заднем плане - явный костыль.

**Comment by hts1238** [comment]
Привет, спасибо за отзыв!
Данный Messenger мы писали как проект в Яндекс Лицее, на которое у нас было очень мало времени, поэтому в нем так много багов. Но мы не собираемся на этом останавливаться. Мы дорабатываем как наше Desktop приложение на Python, так и пишем web-версию нашего мессенджера. Пока работа над ним еще не закончилась, готов только частично дизайн, но функциональности никакой нет. Но вы можете уже посмотреть на него на нашем сайте [messenger.tim-ur.ru/web](url)
